// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlJkWbXcQ0zmG71jKDLr7vttx8f6LIY5E',
    appId: '1:51668859031:web:743768f9b18cd92053d1d2',
    messagingSenderId: '51668859031',
    projectId: 'fire-1d8e4',
    authDomain: 'fire-1d8e4.firebaseapp.com',
    storageBucket: 'fire-1d8e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB65lzn2kUPs-f0i9skP7IyUhxDy_-CWIY',
    appId: '1:51668859031:android:700acfc43e926f7553d1d2',
    messagingSenderId: '51668859031',
    projectId: 'fire-1d8e4',
    storageBucket: 'fire-1d8e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb6DUtSs0X8UdhHQ-_DEiOPspUoxhfgM8',
    appId: '1:51668859031:ios:13761558983c12d853d1d2',
    messagingSenderId: '51668859031',
    projectId: 'fire-1d8e4',
    storageBucket: 'fire-1d8e4.appspot.com',
    iosClientId: '51668859031-qgnibo8mc11ulp7sk022lf38pvikliej.apps.googleusercontent.com',
    iosBundleId: 'com.example.theLastFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb6DUtSs0X8UdhHQ-_DEiOPspUoxhfgM8',
    appId: '1:51668859031:ios:13761558983c12d853d1d2',
    messagingSenderId: '51668859031',
    projectId: 'fire-1d8e4',
    storageBucket: 'fire-1d8e4.appspot.com',
    iosClientId: '51668859031-qgnibo8mc11ulp7sk022lf38pvikliej.apps.googleusercontent.com',
    iosBundleId: 'com.example.theLastFirebase',
  );
}
